FROM cvat/server:latest
USER root
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*
COPY entrypoint-with-init.sh /home/django/entrypoint-with-init.sh
RUN chmod +x /home/django/entrypoint-with-init.sh && chown django:django /home/django/entrypoint-with-init.sh
USER django
CMD ["/home/django/entrypoint-with-init.sh"]
