FROM sooryacvatreg.azurecr.io/cvat-ui:latest as source

FROM nginx:1.25-alpine
COPY --from=source /usr/share/nginx/html /usr/share/nginx/html
COPY --from=source /etc/nginx/mime.types /etc/nginx/mime.types

RUN printf 'server {\n\
    listen 8081;\n\
    root /usr/share/nginx/html;\n\
    server_tokens off;\n\
    gzip on;\n\
    gzip_comp_level 6;\n\
    gzip_types text/html application/javascript text/javascript application/wasm image/x-icon;\n\
    location / {\n\
        try_files $uri $uri/ /index.html;\n\
        add_header Cache-Control "no-cache, no-store, must-revalidate";\n\
        add_header Pragma "no-cache";\n\
        add_header Expires 0;\n\
    }\n\
    location /assets {\n\
        expires 1y;\n\
        add_header Cache-Control "public";\n\
        access_log off;\n\
    }\n\
}\n' > /etc/nginx/conf.d/default.conf

EXPOSE 8081
