FROM sooryacvatreg.azurecr.io/cvat-ui:latest as source
FROM nginx:1.25-alpine
COPY --from=source /usr/share/nginx/html /usr/share/nginx/html
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 8081
